// apps/vue-demo/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Button, Checkbox, Input, Select } from '@design-system/vue';

const darkMode = ref(false);
const email = ref('');
const agreed = ref(false);
const framework = ref('');
const loading = ref(false);

const frameworks = [
  { value: 'react', label: 'React' },
  { value: 'angular', label: 'Angular' },
  { value: 'vue', label: 'Vue' },
  { value: 'svelte', label: 'Svelte' },
];

function toggleDark() {
  darkMode.value = !darkMode.value;
  document.documentElement.setAttribute('data-theme', darkMode.value ? 'dark' : 'light');
}

function handleSubmit() {
  loading.value = true;
  setTimeout(() => { loading.value = false; }, 2000);
}
</script>

<template>
  <div
    :style="{
      minHeight: '100vh',
      backgroundColor: 'var(--bg)',
      color: 'var(--text)',
      padding: '2rem',
      fontFamily: 'system-ui, sans-serif',
    }"
  >
    <header
      :style="{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '2rem',
        paddingBottom: '1rem',
        borderBottom: '1px solid var(--border-color)',
      }"
    >
      <h1 :style="{ fontSize: '1.5rem', fontWeight: 700 }">
        💚 Vue Design System Demo
      </h1>
      <Button intent="ghost" @click="toggleDark">
        {{ darkMode ? '☀️ Light' : '🌙 Dark' }}
      </Button>
    </header>

    <main
      :style="{
        maxWidth: '800px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '2rem',
      }"
    >
      <!-- Buttons -->
      <section>
        <h2 :style="{ marginBottom: '1rem', fontSize: '1.25rem', fontWeight: 600 }">Buttons</h2>
        <div :style="{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem' }">
          <Button intent="primary">Primary</Button>
          <Button intent="secondary">Secondary</Button>
          <Button intent="success">Success</Button>
          <Button intent="warning">Warning</Button>
          <Button intent="danger">Danger</Button>
          <Button intent="ghost">Ghost</Button>
        </div>
        <div :style="{ display: 'flex', gap: '0.75rem', marginTop: '0.75rem' }">
          <Button size="sm">Small</Button>
          <Button size="md">Medium</Button>
          <Button size="lg">Large</Button>
          <Button :is-loading="loading" @click="handleSubmit">
            {{ loading ? 'Loading…' : 'Click to load' }}
          </Button>
        </div>
      </section>

      <!-- Input -->
      <section>
        <h2 :style="{ marginBottom: '1rem', fontSize: '1.25rem', fontWeight: 600 }">Input</h2>
        <div :style="{ display: 'flex', flexDirection: 'column', gap: '1rem', maxWidth: '400px' }">
          <Input
            v-model="email"
            label="Email address"
            type="email"
            placeholder="you@example.com"
            helper-text="We'll never share your email."
          />
          <Input
            label="Password"
            type="password"
            placeholder="Min 8 characters"
            error-message="Password is too short."
          />
          <Input label="Success state" model-value="Valid input" variant="success" />
        </div>
      </section>

      <!-- Select -->
      <section>
        <h2 :style="{ marginBottom: '1rem', fontSize: '1.25rem', fontWeight: 600 }">Select</h2>
        <div :style="{ maxWidth: '400px' }">
          <Select
            v-model="framework"
            label="Favorite framework"
            :options="frameworks"
            placeholder="Choose a framework…"
            helper-text="Pick your favorite JavaScript framework."
          />
        </div>
      </section>

      <!-- Checkbox -->
      <section>
        <h2 :style="{ marginBottom: '1rem', fontSize: '1.25rem', fontWeight: 600 }">Checkbox</h2>
        <div :style="{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }">
          <Checkbox v-model="agreed" label="I agree to the terms and conditions" />
          <Checkbox label="Subscribe to newsletter" helper-text="You can unsubscribe at any time." />
          <Checkbox label="Indeterminate state" :indeterminate="true" />
          <Checkbox label="Disabled checkbox" :disabled="true" />
        </div>
      </section>
    </main>
  </div>
</template>

// apps/angular-demo/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  ButtonComponent,
  CheckboxComponent,
  InputComponent,
  SelectComponent,
} from '@design-system/ng';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ButtonComponent,
    CheckboxComponent,
    InputComponent,
    SelectComponent,
  ],
  template: `
    <div [style.backgroundColor]="'var(--bg)'" [style.color]="'var(--text)'" style="min-height:100vh;padding:2rem;font-family:system-ui,sans-serif;">
      <header style="display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem;padding-bottom:1rem;border-bottom:1px solid var(--border-color);">
        <h1 style="font-size:1.5rem;font-weight:700;">🅰️ Angular Design System Demo</h1>
        <ds-button intent="ghost" (clicked)="toggleDark()">
          {{ darkMode() ? '☀️ Light' : '🌙 Dark' }}
        </ds-button>
      </header>

      <main style="max-width:800px;margin:0 auto;display:flex;flex-direction:column;gap:2rem;">

        <section>
          <h2 style="margin-bottom:1rem;font-size:1.25rem;font-weight:600;">Buttons</h2>
          <div style="display:flex;flex-wrap:wrap;gap:0.75rem;">
            <ds-button intent="primary">Primary</ds-button>
            <ds-button intent="secondary">Secondary</ds-button>
            <ds-button intent="success">Success</ds-button>
            <ds-button intent="warning">Warning</ds-button>
            <ds-button intent="danger">Danger</ds-button>
            <ds-button intent="ghost">Ghost</ds-button>
          </div>
          <div style="display:flex;gap:0.75rem;margin-top:0.75rem;">
            <ds-button size="sm">Small</ds-button>
            <ds-button size="md">Medium</ds-button>
            <ds-button size="lg">Large</ds-button>
            <ds-button [isLoading]="loading()" (clicked)="handleSubmit()">
              {{ loading() ? 'Loading…' : 'Click to load' }}
            </ds-button>
          </div>
        </section>

        <section>
          <h2 style="margin-bottom:1rem;font-size:1.25rem;font-weight:600;">Input</h2>
          <div style="display:flex;flex-direction:column;gap:1rem;max-width:400px;">
            <ds-input label="Email address" type="email" placeholder="you@example.com" helperText="We'll never share your email." />
            <ds-input label="Password" type="password" placeholder="Min 8 characters" errorMessage="Password is too short." />
            <ds-input label="Success state" variant="success" />
          </div>
        </section>

        <section>
          <h2 style="margin-bottom:1rem;font-size:1.25rem;font-weight:600;">Select</h2>
          <div style="max-width:400px;">
            <ds-select
              label="Favorite framework"
              [options]="frameworks"
              placeholder="Choose a framework…"
              helperText="Pick your favorite JavaScript framework."
            />
          </div>
        </section>

        <section>
          <h2 style="margin-bottom:1rem;font-size:1.25rem;font-weight:600;">Checkbox</h2>
          <div style="display:flex;flex-direction:column;gap:0.75rem;">
            <ds-checkbox label="I agree to the terms and conditions" />
            <ds-checkbox label="Subscribe to newsletter" helperText="You can unsubscribe at any time." />
            <ds-checkbox label="Disabled checkbox" [disabled]="true" />
          </div>
        </section>

      </main>
    </div>
  `,
})
export class AppComponent {
  darkMode = signal(false);
  loading = signal(false);

  frameworks = [
    { value: 'react', label: 'React' },
    { value: 'angular', label: 'Angular' },
    { value: 'vue', label: 'Vue' },
    { value: 'svelte', label: 'Svelte' },
  ];

  toggleDark() {
    this.darkMode.update((d) => !d);
    document.documentElement.setAttribute(
      'data-theme',
      this.darkMode() ? 'dark' : 'light'
    );
  }

  handleSubmit() {
    this.loading.set(true);
    setTimeout(() => this.loading.set(false), 2000);
  }
}
