// libs/vue-design-system/src/lib/Checkbox/Checkbox.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    label?: string;
    helperText?: string;
    disabled?: boolean;
    indeterminate?: boolean;
    id?: string;
  }>(),
  {
    modelValue: false,
    label: '',
    helperText: '',
    disabled: false,
    indeterminate: false,
  }
);

const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

const inputRef = ref<HTMLInputElement | null>(null);
const inputId = props.id ?? `ds-checkbox-${Math.random().toString(36).slice(2, 9)}`;

watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) {
      inputRef.value.indeterminate = val ?? false;
    }
  },
  { immediate: true }
);

function onChange(event: Event) {
  emit('update:modelValue', (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <div class="flex flex-col gap-1">
    <label :for="inputId" class="inline-flex items-center gap-2 cursor-pointer select-none text-[var(--text)]">
      <input
        ref="inputRef"
        :id="inputId"
        type="checkbox"
        :checked="modelValue"
        :disabled="disabled"
        :aria-describedby="helperText ? inputId + '-helper' : undefined"
        class="h-4 w-4 rounded border-[var(--border-color)] accent-[var(--color-primary)] focus:ring-[var(--color-primary)] disabled:cursor-not-allowed disabled:opacity-50"
        @change="onChange"
      />
      <span v-if="label" class="text-[var(--font-size-md)]">{{ label }}</span>
    </label>
    <p
      v-if="helperText"
      :id="inputId + '-helper'"
      class="text-[var(--font-size-sm)] text-[var(--text-muted)] ml-6"
    >
      {{ helperText }}
    </p>
  </div>
</template>

// libs/react-design-system/src/lib/Checkbox/Checkbox.tsx
import {
  forwardRef,
  useId,
  useEffect,
  useRef,
  type InputHTMLAttributes,
} from 'react';
import { cn } from '@design-system/utils';

export interface CheckboxProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label?: string;
  indeterminate?: boolean;
  helperText?: string;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ className, label, indeterminate, helperText, id: externalId, ...props }, ref) => {
    const generatedId = useId();
    const id = externalId ?? generatedId;
    const innerRef = useRef<HTMLInputElement>(null);

    const resolvedRef = (ref as React.RefObject<HTMLInputElement>) ?? innerRef;

    useEffect(() => {
      if (resolvedRef && 'current' in resolvedRef && resolvedRef.current) {
        resolvedRef.current.indeterminate = indeterminate ?? false;
      }
    }, [indeterminate, resolvedRef]);

    return (
      <div className="flex flex-col gap-1">
        <label
          htmlFor={id}
          className="inline-flex items-center gap-2 cursor-pointer select-none text-[var(--text)]"
        >
          <input
            ref={resolvedRef}
            type="checkbox"
            id={id}
            className={cn(
              'h-4 w-4 rounded border-[var(--border-color)]',
              'text-[var(--color-primary)]',
              'focus:ring-[var(--color-primary)] focus:ring-offset-0',
              'disabled:cursor-not-allowed disabled:opacity-50',
              'accent-[var(--color-primary)]',
              className
            )}
            aria-describedby={helperText ? `${id}-helper` : undefined}
            {...props}
          />
          {label && (
            <span className="text-[var(--font-size-md)]">{label}</span>
          )}
        </label>
        {helperText && (
          <p
            id={`${id}-helper`}
            className="text-[var(--font-size-sm)] text-[var(--text-muted)] ml-6"
          >
            {helperText}
          </p>
        )}
      </div>
    );
  }
);

Checkbox.displayName = 'Checkbox';
